### ISSUE TITLE
Configuração de firewalld nos profiles

### ISSUE THREAD

**Issue by jairojunior** [puppet-br/pcp-controlrepo#6]
* Puppet Server: 8140
* PuppetDB: 8080 e 8081 (Apenas conexão local)
* PostgreSQL: 5432 (Apenas conexão local)
* Puppet Explorer: 443
* ActiveMQ: 61614 e 61616

**Comment by gutocarvalho** [comment]
Feito!

**Comment by gutocarvalho** [comment]
Suporte a firewalld criado.
